ignore:
  - "examples"
  - "plugins"
  - "scripts"
  - "src/potential/1b/poly*"
  - "src/potential/2b/poly*"
  - "src/potential/3b/poly*"
  - "src/tests"
  - "src/unittests"
  - "src/kdtree"
  - "src/json"
  - "src/Catch2"
  - "src/main"
  - "src/io_tools"
  - "src/potential/electrostatics/files_not_used"
  - "src/potential/electrostatics/helpme.h"
